### ISSUE TITLE
Error al tejer

### ISSUE THREAD

**Issue by wilnellia** [maestria-geotel-201902/unidad-0-asignacion-99-mi-proyecto-wilnellia#1]
Tali, estamos intentando tejer desde anoche y da el siguiente error, hemos verificado todo de arriba abajo y no damos pies con bola, y los códigos al ejecutarlos no dan problemas

![image](https://user-images.githubusercontent.com/56281566/72605960-1bee5000-38f4-11ea-8744-831ccfce9950.png)

**Comment by geofis** [comment]
El área del encabezado yaml es muy delicada. El error indica que espera ":" pero no los encuentra. Se debe a ésto:

>abstract: "Resumen"
Los cambios que se producen en el clima anualmente o de un periodo a otro, se lo podemos atribuir tanto a la variabilidad natural del clima como al cambio que es ocasionado por las actividades antropogénicas. Para poder obtener la significancia de los cambios observados en las provincias de la República Dominica, se analizó la variabilidad pluviométrica de la precipitación, correspondiente al año 1994.


Pero debería estar así:

>abstract: "Resumen. Los cambios que se producen en el clima anualmente o de un periodo a otro, se lo podemos atribuir tanto a la variabilidad natural del clima como al cambio que es ocasionado por las actividades antropogénicas. Para poder obtener la significancia de los cambios observados en las provincias de la República Dominica, se analizó la variabilidad pluviométrica de la precipitación, correspondiente al año 1994."

**Comment by wilnellia** [comment]
Tali, me sigue dando error

![image](https://user-images.githubusercontent.com/56281566/72623380-6800bb00-391b-11ea-9102-8a6094073688.png)

**Comment by geofis** [comment]
Todavía tienes mal escrito el resumen, porque tienes un punto fuera de comillas:

Esta así:

>abstract: "Resumen.Los cambios que se producen en el clima anualmente o de un periodo a otro, se lo podemos atribuir tanto a la variabilidad natural del clima como al cambio que es ocasionado por las actividades antropogénicas. Para poder obtener la significancia de los cambios observados en las provincias de la República Dominica, se analizó la variabilidad pluviométrica de la precipitación, correspondiente al año 1994".

Pero debería estar así (tal como lo puse en mi comentario anterior):

>abstract: "Resumen.Los cambios que se producen en el clima anualmente o de un periodo a otro, se lo podemos atribuir tanto a la variabilidad natural del clima como al cambio que es ocasionado por las actividades antropogénicas. Para poder obtener la significancia de los cambios observados en las provincias de la República Dominica, se analizó la variabilidad pluviométrica de la precipitación, correspondiente al año 1994."

**Comment by wilnellia** [comment]
Tali, todo iba bien hasta que me salio esto. 

![image](https://user-images.githubusercontent.com/56281566/72630395-9d5fd580-3928-11ea-975f-c6cf2fc03a74.png)

**Comment by geofis** [comment]
Lo que se coloca en el archivo `bibliography.bib` no es la referencia tal como quieres que aparezca en tu documento, sino una entrada BibTex que luego llamas mediante `@etiquetadelareferencia` (más detalles en el [vídeo](https://drive.google.com/open?id=1OGq3JcmM-6EKJ506g_MOBEeIiCzpjoW4)).

Si te fijas, tienes dos errores en dicho archivo:

```
@article{García-Páez, Fernando, & Cruz-Medina, Isidro R.. (2009). Variabilidad de la precipitación pluvial en la región Pacífico Norte de México. Agrociencia, 43(1), 1-9. Recuperado en 16 de enero de 2020, de http://www.scielo.org.mx/scielo.php?script=sci_arttext&pid=S1405-31952009000100001&lng=es&tlng=es.}
}
@pagina{http://onamet.gob.do/index.php/sobre-nosotros/quienes-somos}
}
```

Cuando lo que deberías tener son entradas BibTex, como por ejemplo la que te transcribo a continuación, que aplica para el primer texto.

```
@article{garcia2009variabilidad,
  title={Variabilidad de la precipitaci{\'o}n pluvial en la regi{\'o}n Pac{\'\i}fico norte de M{\'e}xico},
  author={Garc{\'\i}a-P{\'a}ez, Fernando and Cruz-Medina, Isidro R},
  journal={Agrociencia},
  volume={43},
  number={1},
  pages={1--9},
  year={2009},
  publisher={Colegio de Postgraduados}
}
```

Para la página de ONAMET tendrías que escribir tu propia entrada Bibtex.

En [este vídeo](https://drive.google.com/open?id=1OGq3JcmM-6EKJ506g_MOBEeIiCzpjoW4) expliqué cómo usar las referencias.
